config/routes.rb
routes = lambda do
  match '/email_to_friend/:type/:id' => 'email_sender#send_mail', as: :email_to_friend, via: [:get, :post]

  namespace :admin do
    resource :captcha_settings
  end
end

if Spree::Core::Engine.respond_to?(:add_routes)
  Spree::Core::Engine.add_routes(&routes)
else
  Spree::Core::Engine.routes.draw(&routes)
end

app/models/spree/captcha_configuration.rb
class Spree::CaptchaConfiguration < Spree::Preferences::Configuration
  THEMES = %w(red white blackglass clean custom)

  # These keys works for localhost.
  preference :private_key, :string,  default: '6LfIsgEAAAAAAGfB6Z0lEUtdL3GVuBkRa9cYlMZz'
  preference :public_key,  :string,  default: '6LfIsgEAAAAAALpT20eiC3RslZQmmCbiNS-AUvSe'
  preference :theme,       :string,  default: 'red'
  preference :use_captcha, :boolean, default: true
end

app/models/spree/mail_to_friend.rb
class Spree::MailToFriend
  include ActiveModel::Validations
  include ActiveModel::Conversion
  attr_accessor :host, :subject, :sender_name, :sender_email, :recipient_name, :recipient_email, :message, :recipients, :invalid_recipients

  EMAILREGEX = /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,8}\z/i

  validates :subject, :sender_name, presence: true
  validates :recipient_name, presence: true, unless: :is_multi
  validates :sender_email, format: { with: EMAILREGEX }
  validates :recipients, length: { minimum: 1, message: Spree.t(:recipients, scope: :validation) }
  validates :invalid_recipients, length: { maximum: 0, message: Spree.t(:invalid_recipients, scope: :validation) }

  def initialize(opts = {})
    @sender_email = opts[:sender_email] || ' '
    @sender_name  = opts[:sender_name]  || @sender_email.split('@', 2)[0].titleize
    @subject      = opts[:subject]      || Spree.t(:sender_subject, scope: :email_to_friend, sender_name: @sender_name, site: site_url)

    @recipients = []
    @invalid_recipients = []

    addresses = (opts[:recipient_email] || '').gsub(';', ',').gsub(/\s/, '')
    addresses.split(',').each do |address|
      if address =~ EMAILREGEX
        @recipients << address
      else
        @invalid_recipients << address
      end
    end

    @recipient_name = opts[:recipient_name]
    @recipient_name ||= @recipients[0].split('@', 2)[0].titleize unless @recipients.empty?

    @message = opts[:message]
  end

  def persisted?
    false
  end

  def is_multi
    [@recipients, @invalid_recipients].compact.sum.size > 1
  end

  private

  def site_url
    Spree::Store.current.try(:url)
  end
end

app/controllers/spree/admin/captcha_settings_controller.rb
module Spree
  module Admin
    class CaptchaSettingsController < BaseController
      def update
        Spree::Captcha::Config.set(params[:preferences])

        respond_to do |format|
          format.html { redirect_to edit_admin_captcha_settings_path }
        end
      end
    end
  end
end

app/controllers/spree/email_sender_controller.rb
class Spree::EmailSenderController < Spree::StoreController
  helper Spree::StoreHelper
  helper Spree::BaseHelper

  before_action :find_object

  def send_mail
    if request.get?
      @mail_to_friend = Spree::MailToFriend.new(sender_email: spree_current_user.try(:email))
    else
      mail_to_friend
    end
  end

  private

    def mail_to_friend
      @mail_to_friend = Spree::MailToFriend.new(params[:mail_to_friend])
      @mail_to_friend.host = request.env['HTTP_HOST']
      respond_to do |format|
        format.html do
          captcha_passed = !Spree::Captcha::Config[:use_captcha] || verify_recaptcha(private_key: Spree::Captcha::Config[:private_key])
          if @mail_to_friend.valid? && captcha_passed
            flash[:notice] = Spree.t('email_to_friend.mail_sent_to', email: @mail_to_friend.recipients.join(', '))

            send_message(@object, @mail_to_friend)

            method_name = "after_delivering_#{@object.class.name.downcase}_mail"
            send(method_name) if respond_to?(method_name, true)

            redirect_to @object
          else
            render action: :send_mail
          end
        end
      end
    end

    # Extract send message to make easier to override
    def send_message(object, mail_to_friend)
      Spree::ToFriendMailer.mail_to_friend(object, mail_to_friend).deliver_now
    end

    def find_object
      class_name = "Spree::#{(params[:type].titleize)}".constantize
      return false if params[:id].blank?

      if class_name.respond_to?('find_by_slug')
        @object ||= class_name.find_by_slug(params[:id])
      end
      if class_name.respond_to?('get_by_param')
        @object ||= class_name.get_by_param(params[:id])
      end

      # Final attempt to load by id.
      @object ||= class_name.find_by_id(params[:id])

      # Display 404 page if object is not found.
      raise ActiveRecord::RecordNotFound if @object.nil?
    end
end

app/views/spree/admin/captcha_settings/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t('captcha.captcha_settings') %>
<% end %>

<%= form_tag(admin_captcha_settings_path, method: :put) do |f| -%>

  <fieldset>
    <div data-hook="admin_captcha_settings" class="row">

      <div class="form-group choices">
        <%= label_tag Spree.t('captcha.use_captcha') %>
        <div class="inline-radio">
          <%= label_tag do %>
            <%= radio_button_tag 'preferences[use_captcha]', true, Spree::Captcha::Config[:use_captcha] %>
            <%= Spree.t(:yes) %>
          <% end %>

          <%= label_tag do %>
            <%= radio_button_tag 'preferences[use_captcha]', false, !Spree::Captcha::Config[:use_captcha] %>
            <%= Spree.t(:no) %>
          <% end %>
        </div>
      </div>

      <div data-hook="public_key" class="form-group">
        <%= label_tag Spree.t('captcha.public_key') %>
        <%= text_field_tag 'preferences[public_key]', Spree::Captcha::Config[:public_key], class: 'control-form' %>
      </div>

      <div data-hook="private_key" class="form-group">
        <%= label_tag Spree.t('captcha.private_key') %>
        <%= text_field_tag 'preferences[private_key]', Spree::Captcha::Config[:private_key], class: 'control-form' %>
      </div>

      <div data-hook="theme" class="form-group">
        <%= label_tag Spree.t('captcha.theme') %>
        <%= select_tag 'preferences[theme]', options_for_select(Spree::CaptchaConfiguration::THEMES, Spree::Captcha::Config[:theme]), class: 'select2' %>
      </div>

    </div>

    <div class="form-actions actions" data-hook="buttons">
      <%= button Spree.t(:update), 'update' %>
    </div>

  </fieldset>

<% end -%>

app/views/spree/email_sender/send_mail.html.erb
<h1><%= Spree.t('email_to_friend.tell_about', product: @object.name) %></h1>

<%= form_for(@mail_to_friend, url: email_to_friend_path(params[:type], @object)) do |f| -%>
  <%= render 'spree/shared/error_messages', target: @mail_to_friend %>
  <p>
    <%= f.label(:sender_name, Spree.t('email_to_friend.sender_name')) %><br/>
    <%= f.text_field(:sender_name) %>
  </p>
  <p>
    <%= f.label(:sender_email, Spree.t('email_to_friend.sender_email')) %><br/>
    <%= f.text_field(:sender_email) %>
  </p>
  <p>
    <%= f.label(:recipient_name, Spree.t('email_to_friend.recipient_name')) %><br/>
    <%= f.text_field(:recipient_name) %>
  </p>
  <p>
    <%= f.label(:recipient_email, Spree.t('email_to_friend.recipient_email')) %><br/>
    <%= f.text_field(:recipient_email) %>
  </p>
  <p>
    <%= f.label(:message, Spree.t('email_to_friend.message')) %><br/>
    <%= f.text_area(:message) %>
  </p>
  <% if Spree::Captcha::Config[:use_captcha] %>
    <%= recaptcha_tags public_key: Spree::Captcha::Config[:public_key], display: { theme: Spree::Captcha::Config[:theme] } %>
  <% end %>
  <p>
    <%= f.submit Spree.t('email_to_friend.send_message') %>
  </p>
<% end -%>

app/views/spree/products/_mail_to_friend.text.erb
<%= @mail.recipient_name %>,

<%= Spree.t(:you_would_like_this_item, scope: :email_to_friend) %>

  * <%= @object.name %>

<% unless @mail.message.blank? -%>
<%= @mail.message %>
<% end -%>

<%= @mail.sender_name %>

<%= Spree.t(:click_link_to_view, scope: :email_to_friend, name: @object.name) %>
<%= spree.product_url(@object) %>

<%= Spree.t(:visit_page, scope: :email_to_friend, url: spree.products_url) %>